[project]
name = "nyctrains"
description = "Python tools and FastAPI backend for MTA GTFS-RT subway and LIRR data"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Mikael Moise", email = "mikaelmoise00@gmail.com" }]
dynamic = ["version"]
dependencies = [
    "fastapi",
    "gtfs-realtime-bindings",
    "httpx",
    "yc-protobuf3-to-dict",
    "pydantic",
    "python-dotenv",
    "requests",
    "uvicorn",
    "protobuf",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]
keywords = [
    "data",
    "trains",
    "data science",
    "data engineering",
    "api"
]
[project.urls]
"Repository" = "https://github.com/arrismo/nyctrains"
"Bug Tracker" = "https://github.com/arrismo/nyctrains/issues"

[project.optional-dependencies]
test = [
    "pytest>=8.3.5",
    "pytest-cov"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
include = ["nyctrains*"]
